package com.linlishi.spring.jdbc.tempalate.orm.consts;

public class SqlKeys {
	public static final String WHERE = "WHERE";
	public static final String _WHERE_ = " WHERE ";
	public static final String WHERE_ = "WHERE ";
	public static final String _AND_ = " AND ";
	public static final String _OR_ = " OR ";
	public static final String _NOT_ = " NOT ";
	public static final String NOT = "NOT";
	public static final String ALWAYS_TRUE = "1 > 0";
	public static final String ALWAYS_FALSE = "0 > 1";
	public static final String PARA = "?";
	public static final String _ASC = " ASC";
	public static final String _DESC = " DESC";
	public static final String SELECT_ = "SELECT ";
	public static final String SELECT_ALL_ = "SELECT * ";
	public static final String UPDATE_ = "UPDATE ";
	public static final String INSERT_INTO_ = "INSERT INTO ";
	public static final String DELETE_ = "DELETE ";
	public static final String ALTER_TABLE_= "ALTER TABLE ";
	public static final String COUNT_ALL = "COUNT(*)";
	public static final String COUNT = "COUNT";
	public static final String COUNT_ = "COUNT ";
	public static final String FROM = "FROM";
	public static final String FROM_ = "FROM ";
	public static final String _FROM_ = " FROM ";
	public static final String LEFT_JOIN_ = "LEFT JOIN ";
	public static final String INNER_JOIN_ = "INNER JOIN ";
	public static final String GROUP_BY = "GROUP BY";
	public static final String GROUP_BY_ = "GROUP BY ";
	public static final String _GROUP_BY_ = " GROUP BY ";
	public static final String HAVING_ = "HAVING ";
	public static final String _HAVING_ = "_HAVING_";
	public static final String FOR_UPDATE = "FOR UPDATE";
	public static final String _FOR_UPDATE = " FOR UPDATE";
	public static final String _ON_ = " ON ";
	public static final String SET_ = "SET ";
	public static final String _SET_ = " SET ";
	public static final String _VALUES_ = " VALUES ";
	public static final String VALUES_ = "VALUES ";
	public static final String _LIMIT_ = " LIMIT ";
	public static final String LIMIT = "LIMIT";
	public static final String LIMIT_ = "LIMIT ";
	public static final String ORDER_BY = "ORDER BY";
	public static final String _ORDER_BY_ = " ORDER BY ";
	public static final String ORDER_BY_ = "ORDER BY ";
	public static final String COMMA_ = ", ";
	public static final String _EQ_PARA = " = ?";
	public static final String _EQ_ = " = ";
	public static final String EQ = "=";
	public static final String _LIKE_ = " LIKE ";
	public static final String LIKE = "LIKE";
	public static final String _LIKE_PARA = " LIKE ?";
	public static final String LE = "<=";
	public static final String _LE_ = " <= ";
	public static final String _LE_PARA = " <= ?";
	public static final String GE = ">=";
	public static final String _GE_ = " >= ";
	public static final String _GE_PARA = " >= ?";
	public static final String LT = "<";
	public static final String _LT_ = " < ";
	public static final String _LT_PARA = " < ?";
	public static final String GT = ">";
	public static final String _GT_ = " > ";
	public static final String _GT_PARA = " > ?";
	public static final String NE = "<>";
	public static final String _NE_ = " <> ";
	public static final String _NE_PARA = " <> ?";
	public static final String BT = "BETWEEN";
	public static final String _BT_ = " BETWEEN ";
	public static final String _BT_PARA = " BETWEEN ? AND ?";
	public static final String NBT = "NOT BETWEEN";
	public static final String _NBT_ = " NOT BETWEEN ";
	public static final String _NBT_PARA = " NOT BETWEEN ? AND ?";
	public static final String ISNULL = "IS NULL";
	public static final String _ISNULL = " IS NULL";
	public static final String ISNOTNULL = "IS NOT NULL";
	public static final String _ISNOTNULL = " IS NOT NULL";
	public static final String ISTRUE = "IS TRUE";
	public static final String _ISTRUE = " IS TRUE";
	public static final String _ISNOTTRUE = " IS NOT TRUE";
	public static final String ISNOTTRUE = "IS NOT TRUE";
	public static final String IN = "IN";
	public static final String _IN_ = " IN ";
	public static final String NOTIN = "NOT IN";
	public static final String _NOTIN_ = " NOT IN ";
	public static final String DISTINCT_ = "DISTINCT ";
	public static final String UNUSED_ALIAS = "unused_$_";
	public static final String LEFT_PARENTHESIS = "(";
	public static final String RIGHT_PARENTHESIS = ")";
	public static final String _PLUS_ = " + ";
	public static final String _PLUS_PARA = " + ?";
	public static final String _MINUS_ = " - ";
	public static final String _MINUS_PARA = " - ?";
	public static final String SUM = "SUM";
	public static final String _AS_ = " AS ";
	public static final String TRUE = "1";
	public static final String FALSE = "0";
}
